# Generated by Django 3.1.1 on 2020-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Cateogary', models.CharField(max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=1000)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='icommerce/images')),
            ],
        ),
    ]
