# Generated by Django 3.1.1 on 2020-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icommerce', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
