# Generated by Django 3.1.1 on 2020-09-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icommerce', '0003_auto_20200915_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
