# Generated by Django 3.1.1 on 2020-09-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icommerce', '0004_auto_20200915_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
    ]
