# Generated by Django 3.1.1 on 2020-09-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icommerce', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linkToDownload',
            field=models.URLField(default=''),
        ),
    ]
