# Generated by Django 3.1.1 on 2020-09-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icommerce', '0007_product_linktodownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='linkToDownload',
            field=models.CharField(default='', max_length=500),
        ),
    ]
